- name: kubeadm_install
  hosts: controlplane_nodes
  debugger: on_failed
  become: true
  tasks:
    - name: Ensure prerequisit packages are present
      apt:
        pkg:
          - gpg
          - curl
          - apt-transport-https
          - ca-certificates
    - name: Check repository and create if does not exist
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Installing dep
      ansible.builtin.shell:
        cmd: |
          set -o pipefail &&
          echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" |
          sudo tee /etc/apt/sources.list.d/kubernetes.list &&
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg &&
          sudo apt-get update
      args:
        executable: /bin/bash
        creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    - name: Install k8s components
      apt:
        pkg:
          - kubelet
          - kubeadm
          - kubectl
    - name: Enable ipv4 forwarding
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: net.ipv4.ip_forward = 1
        create: true
        mode: '0644'
    - name: Download ContainerD files
      ansible.builtin.get_url:
        url: https://github.com/containerd/containerd/releases/download/v1.7.18/containerd-1.7.18-linux-amd64.tar.gz
        dest: /tmp
        mode: '0550'
        checksum: sha256:https://github.com/containerd/containerd/releases/download/v1.7.18/containerd-1.7.18-linux-amd64.tar.gz.sha256sum
      register: download_result
    - name: Extract ContainerD Files
      ansible.builtin.unarchive:
        src: "{{ download_result.dest }}"
        dest: /usr/local
        remote_src: true
